config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('', lambda x: redirect('manga_list')),
    path('admin/', admin.site.urls),
    path('manga/', include('ImageLib.urls')),
    path('profile/', include('users.urls'))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from users.views import RegisterView, ProfileUpdateView

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('<int:pk>/', ProfileUpdateView.as_view(), name='user_profile_update'),
    path('register/', RegisterView.as_view(), name='register'),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

ImageLib/models.py
from django.db import models
import datetime

YEAR_CHOICES = [(r, r) for r in range(1945, datetime.date.today().year + 1)]


def manga_cover_directory_path(instance, filename):
    extension = filename.split('.')[-1]
    manga_name = instance.name
    filename = f"{manga_name}_cover.{extension}"
    return f"{manga_name}/cover/{filename}"


def Volume_cover_directory_path(instance, filename):
    extension = filename.split('.')[-1]
    manga_name = instance.manga.name
    filename = f"{manga_name}_{instance.number}.{extension}"
    return f"{manga_name}/Vol_{instance.number}/Cover/{filename}"


def Chapter_directory_path(instance, filename):
    extension = filename.split('.')[-1]
    manga_name = instance.chapter.volume.manga.name
    volume = instance.chapter.volume.number
    filename = f"{instance.number}.{extension}"
    return f"{manga_name}/Vol_{volume}/Ch_{instance.chapter.number}/{filename}"


class Author(models.Model):
    first_name = models.CharField(max_length=255, verbose_name="Имя")
    last_name = models.CharField(max_length=255, verbose_name="Фамилия")
    Date_of_Birth = models.DateField(verbose_name="Дата рождения")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = "Авторы"


class ReleaseFormat(models.Model):
    name = models.CharField(max_length=255, verbose_name="Формат выпуска")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Формат выпуска'
        verbose_name_plural = "Форматы выпуска"


class Painter(models.Model):
    first_name = models.CharField(max_length=255, verbose_name="Имя")
    last_name = models.CharField(max_length=255, verbose_name="Фамилия")
    Date_of_Birth = models.DateField(verbose_name="Дата рождения")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name = 'Художник'
        verbose_name_plural = "Художники"


class Genre(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = "Жанры"


STATUS_CHOICES = (
    ("finished", "завершен"),
    ("continue", "продолжается")
)


class Manga(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=5000, verbose_name="Описание")

    release_year = models.IntegerField(
        choices=YEAR_CHOICES,
        default=datetime.datetime.now().year,
        verbose_name="Год выпуска"
    )

    status = models.CharField(choices=STATUS_CHOICES, max_length=100, verbose_name="Статус")
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name="Автор")
    painter = models.ForeignKey(Painter, on_delete=models.CASCADE, verbose_name="Художник")
    release_format = models.ManyToManyField(ReleaseFormat, verbose_name="Формат выпуска")
    manga_cover = models.ImageField(upload_to=manga_cover_directory_path, verbose_name="Обложка манги")
    genres = models.ManyToManyField(Genre, verbose_name="Жанры", blank=True)

    def get_ordered_related_volumes(self):
        return self.volume_set.all().order_by("number")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Произведение'
        verbose_name_plural = "Произведения"


class Volume(models.Model):
    number = models.PositiveSmallIntegerField()
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE,
                              verbose_name="Произведение")

    # Volume_cover = models.ImageField(upload_to = Volume_cover_directory_path, verbose_name = "Обложка тома")

    def __str__(self):
        return f"{self.number}"

    def get_ordered_volumes(self):
        return Volume.objects.all().order_by("number")

    def get_ordered_related_chapters(self):
        return self.chapter_set.all().order_by("number")

    def get_next_volume_chapter(self):
        volume = Volume.objects.filter(number__gt=self.number, manga=self.manga).order_by("number").first()
        chapter = None
        if volume:
            chapter = volume.chapter_set.all().order_by("number").first()
        else:
            volume = Volume.objects.filter(manga=self.manga).order_by('number').last()
            if volume.pk == self.pk:
                # chapter = volume.chapter_set.all().order_by("number").first()
                return None

        if chapter:
            return {
                'volume': volume,
                'chapter': chapter,
                'volume_id': volume.pk,
                'chapter_id': chapter.pk
            }

        return None

    def get_prev_volume_chapter(self):
        volume = Volume.objects.filter(number__lt=self.number, manga=self.manga).order_by("number").last()
        chapter = None
        if volume:
            chapter = volume.chapter_set.all().order_by("number").last()
        else:
            volume = Volume.objects.filter(manga=self.manga).order_by('number').first()
            if volume.pk == self.pk:
                # chapter = volume.chapter_set.all().order_by("number").last()
                return None

        if chapter:
            return {
                'volume': volume,
                'chapter': chapter,
                'volume_id': volume.pk,
                'chapter_id': chapter.pk
            }

        return None

    class Meta:
        verbose_name = 'Том'
        verbose_name_plural = "Тома"


class Chapter(models.Model):
    title = models.CharField(max_length=255, verbose_name="Название главы")
    number = models.PositiveSmallIntegerField(verbose_name="Номер главы")
    volume = models.ForeignKey(Volume, on_delete=models.CASCADE, verbose_name="Том", null=True, blank=True)

    def __str__(self):
        return f"{self.number}"

    def get_next_chapter(self):
        queryset = Chapter.objects.filter(number__gt=self.number, volume=self.volume).order_by("number").first()
        return queryset

    def get_prev_chapter(self):
        queryset =  Chapter.objects.filter(number__lt=self.number, volume=self.volume).order_by("number").last()
        return queryset
    def get_ordered_chapters(self):
        return Volume.objects.all().order_by("number")

    def get_ordered_related_pages(self):
        return self.page_set.all().order_by("number")

    class Meta:
        verbose_name = 'Глава'
        verbose_name_plural = "Главы"


class Page(models.Model):
    number = models.PositiveSmallIntegerField(verbose_name="Номер страницы")
    image = models.ImageField(upload_to=Chapter_directory_path, verbose_name="Страница")
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, verbose_name="Глава")

    def __str__(self):
        return f"{self.number}"

    class Meta:
        verbose_name = 'Страница'
        verbose_name_plural = "Страницы"

users/models.py
import uuid

import sys

sys.path.append('..')

from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.utils import timezone
from django.dispatch import receiver
from django.contrib.auth import get_user_model

from ImageLib.models import Manga, Page


class UserManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, nickname, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(nickname, email, password, **extra_fields)

    def create_superuser(self, nickname, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(nickname, email, password, **extra_fields)

    def _create_user(self, nickname, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, nickname=nickname, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user


def user_directory_path(instance, filename):
    extension = filename.split('.')[-1]
    filename = f"{uuid.uuid4()}.{extension}"
    return f"profiles/{timezone.now().date().strftime('%Y/%m/%d')}/{filename}"


class User(AbstractBaseUser, PermissionsMixin):
    nickname = models.CharField(
        max_length=255,
        help_text="Full name/alias/nickname as you would usually sign your emails, "
                  "e.g. John Johnson or Lord Demogorgon."
    )
    email = models.EmailField(
        unique=True,
        help_text="The email address of the main label. It will be needed for logging in."
    )
    avatar = models.ImageField(upload_to=user_directory_path, blank=True, verbose_name="avatar")
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nickname']

    objects = UserManager()

    def __str__(self):
        return f"{self.nickname} ({self.email})"

    def delete(self, using=None, keep_parents=False):
        self.image.delete()
        super().delete()

    class Meta:
        verbose_name = 'Системный пользователь'
        verbose_name_plural = "Системные пользователи"


@receiver(models.signals.pre_save, sender=User)
def auto_delete_file_on_change(sender, instance, **kwargs):
    if not instance.pk:
        return False

    try:
        old_file = User.objects.get(pk=instance.pk).avatar
    except User.DoesNotExist:
        return False

    if old_file:
        models.signals.pre_save.disconnect(auto_delete_file_on_change, sender=sender)
        old_file.delete()
        models.signals.pre_save.connect(auto_delete_file_on_change, sender=sender)


class ProfileMangaLibraryItem(models.Model):
    status_states = [(1, 'featured_manga'),
                     (2, 'closed_manga'),
                     (3, 'read_manga'),
                     (4, 'abandoned_manga'),
                     (5, 'planned_manga')]

    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Владелец')
    status = models.CharField(max_length=255, choices=status_states, verbose_name='Статус')
    manga = models.ManyToManyField(Manga, verbose_name='Избранная манга')


# class Profile(models.Model):
#     owner = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, verbose_name='Владелец')


class Comment(models.Model):
    comment = models.CharField(max_length=777, verbose_name='Комментарий')
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Автор комментария')
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    likes = models.PositiveIntegerField(default=0, verbose_name='Количество согласных')
    dislikes = models.PositiveIntegerField(default=0, verbose_name='Количество не согласных')

    class Meta:
        abstract = True


class PageComment(Comment):
    page = models.ForeignKey(Page, on_delete=models.CASCADE, verbose_name='манга')


class MangaComment(Comment):
    manga = models.ForeignKey(Manga, on_delete=models.CASCADE, verbose_name='манга')

ImageLib/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.forms.widgets import CheckboxSelectMultiple, ClearableFileInput, FileInput

from .models import Manga, Chapter, Volume, Page, Painter, Author


ZIP_FORMAT = "zip,application/octet-stream,application/zip,application/x-zip,application/x-zip-compressed"


class MangaForm(forms.ModelForm):
    class Meta:
        model = Manga
        fields = [
            "name", "description", "release_year", "status", "author",
            "painter", "genres", "release_format", "manga_cover"
        ]

        widgets = {
            'release_format': CheckboxSelectMultiple(),
        }


class VolumeForm(forms.ModelForm):
    class Meta:
        model = Volume
        fields = ["number", "manga"]


class PainterForm(forms.ModelForm):
    class Meta:
        model = Painter
        fields = ["first_name", "last_name", "Date_of_Birth"]


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ["first_name", "last_name", "Date_of_Birth"]


class ChapterForm(forms.ModelForm):
    class Meta:
        model = Chapter
        fields = ["title", "volume", "number"]


class ChapterQuickForm(forms.ModelForm):
    manga = forms.ModelChoiceField(label="Манга", queryset=Manga.objects.all())
    images = forms.FileField(label="Страницы/Архив", required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            is_file = type(visible.field.widget) in [FileInput, ClearableFileInput]
            if is_file:
                visible.field.widget.attrs["accept"] = ZIP_FORMAT

    class Meta:
        model = Chapter
        fields = ["manga", "volume", "title", "number", "images"]


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ["number", "image"]


PagesFormSet = inlineformset_factory(
    Chapter,
    Page,
    form=PageForm,
    extra=0,
    can_delete=False,
    can_delete_extra=False,
)

templates/chapter/chapter_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags custom_tags_extra %}

{% block content %}
    <div class="d-flex w-100 justify-content-center py-4">
        <form enctype="multipart/form-data" class="container" method="post" id="product_form">
            {% csrf_token %}
            <div class="card">
                <div class="card-header card-header-secondary">
                    <h4 class="card-title">Add Chapter</h4>
                </div>
                {% for field in form %}
                <div class="form-group card-body">
                    {% if field.name == 'volume'%}

                    <label>{{ field.label }}</label>
                    {% if field.field.required %}
                        <span style="color: red;" class="required">*</span>
                    {% endif %}
                    <select name="{{ field.html_name }}" required id="{{ field.id_for_label }}">
                        {% for choice in field %}
                            {% if forloop.first %}
                                <option value="{{ choice.data.value }}">{{ choice.choice_label }}</option>
                            {% else %}
                                {% if form.instance.volume.pk != choice.data.value %}
                                    <option value="{{ choice.data.value }}" hidden manga_id="{{form.fields|get:'volume'|get_attr:'queryset'|get:forloop.counter0|get_attr:'manga'|get_attr:'pk'}}">{{ choice.choice_label }}</option>
                                {% elif form.instance.volume.manga.pk == form.fields|get:'volume'|get_attr:'queryset'|get:forloop.counter0|get_attr:'manga'|get_attr:'pk' %}
                                    <option value="{{ choice.data.value }}" selected>{{ choice.choice_label }}</option>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </select>

                    {% else %}
                    <label>{{field.label}}</label>
                    {% if field.field.required %}
                    <span style="color: red;" class="required">*</span>
                    {% endif %}

                    {{field}}
                    {% endif %}
                    {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
            {{ formset.management_form }}
            <script type="text/html" id="pages-template">
                <tr id="pages-__prefix__" class= hide_all>
                    {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                    {% endfor %}

                    {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                    {% endfor %}
                </tr>
            </script>

            <div class="table-responsive card mt-4">
                <div class="card-header card-header-secondary">
                    <h4 class="card-title">Add Page</h4>
                </div>
                <table class="table card-body">
                    <thead class="text-secondary">
                    <th>Page <span style="color: red;" class="required">*</span></th>
                    <th></th>
                    <th>Custom Delete btn</th>
                    </thead>
                    <tbody id="item-pages">
                    {% for error in formset.non_form_errors %}
                    <span style="color: red">{{ error }}</span>
                    {% endfor %}
                    {% for forms in formset %}
                    {{ forms.management_form }}
                    <tr id="pages-{{ forloop.counter0 }}" class= hide_all>
                        {{ forms.id }}
                        {% for field in forms.visible_fields %}
                        <td>
                            {{field}}
                            {% for error in field.errors %}
                            <span style="color: red">{{ error }}</span>
                            {% endfor %}
                        </td>
                        {% endfor %}
                        {% if forms.instance.pk %}
                        <td>
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal{{forms.instance.pk}}">
                                Delete
                            </button>
                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal{{forms.instance.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{forms.instance.pk}}" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel{{forms.instance.pk}}">Are Your Sure You Want To Delete This?</h5>
                                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-footer">
                                            <a href="{% url 'chapter_delete' forms.instance.pk %}" type="button" class="btn btn-primary">Yes, Delete</a>
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <button type="button" id="add-page-button" class="btn btn-secondary add-pages">Добавить</button>
            </div>
            <h1></h1>
            <div class="form-group">
                <button type="submit" class="btn btn-secondary btn-block">Сохранить</button>
            </div>
        </form>
    </div>
{% endblock %}


{% block script %}
<script type="text/javascript">
        $(document).ready(function() {
          $('.add-pages').click(function(ev) {
              ev.preventDefault();
              var count = $('#item-pages').children().length;
              var tmplMarkup = $('#pages-template').html();
              var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
              $('#item-pages').append(compiledTmpl);

              // update form count
              $('#id_pages-TOTAL_FORMS').attr('value', count+1);
          });

          var manga_select = $('#id_manga');
          var volume_select = $("option[manga_id]").filter(function() {
            var result = this.getAttribute("manga_id") == manga_select.val();
            if(result){
                return result;
                }
            else{
                this.setAttribute("hidden","");
                return false;
                };
            });
          for(let i=0; i < volume_select.length; i++) {
            volume_select[i].removeAttribute("hidden");
          };

          $('#id_manga').on('change', function() {
    <!--      var manga_select = $("option:not([manga_id],[selected]) + [value]");-->
    <!--      var manga_select = $("#id_manga > option:not([selected])");-->
          var manga_select = $('#id_manga');
          var volume_select_all = $('#id_volume');
          var volume_select = $("option[manga_id]").filter(function() {
            var result = this.getAttribute("manga_id") == manga_select.val();
            if(result){
                return result;
                }
            else{
                this.setAttribute("hidden","");
                return false;
                };
            });
          volume_select_all.val(null);
          for(let i=0; i < volume_select.length; i++) {
            volume_select[i].removeAttribute("hidden");
          };
        });
        $("input#id_images").on('change', function() {
        var formset_inputs = $('div.table-responsive.card.mt-4').find('button,input');
        console.log(formset_inputs);
        var status = Boolean($(this).val());
        console.log(status);
        console.log(formset_inputs.length);
        for(let i=0; i < formset_inputs.length; i++) {
            console.log(formset_inputs[i]);
            $(formset_inputs[i]).prop('disabled', status);
        };
        });
        });
    </script>
{% endblock %}